# JUST A SAMPLE CONFIG FILE FOR REFERENCE. CREATE YOUR OWN config/db-config.ini AND FILL IN THE REAL VALUES.
servername = "127.0.0.1"
username = "root"
password = "YOUR_REAL_PASSWORD"  ; Replace with your actual database password
dbname = "db_atheneum"